### PR TITLE
remove readonly label and load pages on demand

### PR DESCRIPTION
**Pull request by bhamacher**

### CODE REVIEW

**Comment by schnitzeltony** [comment]
Please get waitPopup working again - Otherwise user has zero feedback.

**Comment by schnitzeltony** [comment]
Seems json state is gone:
qrc:/qml/pages/SourceModuleTabPage.qml:98: Error: Cannot assign to non-existent property "jsonState"

**Comment by schnitzeltony** [comment]
Fix is simple and I am keen for this change. So will follow up.

Anyway: Thanks this is a major enhancement

**Comment by bhamacher** [comment]
As far as I can tell you already fixed all issues?

**Pull request merged**
